name: Build and Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types: [requested]
    branches: ['main']

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion === 'success' }}

    strategy:
      matrix:
        node-version: [16.x]
  
    steps:
      - uses: actions/checkout@v3
      - name: Usar Node.js versão ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Instalar dependencias
        run: |
          npm ci
          npm run build
      
      - name: Deploy no Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist