name: Validation && CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        node
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
          if (${changed_file}.includes(".spec")) console.log("tem testes presentes")
        .exit
        done

  run-tests:
    needs: validate-changes

    runs-on: ubuntu-latest

    steps:
    # Setup Job
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    # Commands
    - run: npm i
    - run: npm run test