name: actions CI

on: 
  pull_request:
    branches: ['main']

jobs:
  run-tests:
    runs-on: ubuntu-latest
  
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Instalando dependencias
      run: npm i
      run: npm run test