name: actions CI

on: 
  pull_request:
    branches: ['main']

jobs:
  run-tests:
    runs-on: ubuntu-latest
  
  steps:
    - name: Setup Nodejs
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      
    - name: Instalando dependencias
    - run: npm i
    - run: npm run test