name: Deploy MAS
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_OUTPUT
        fi
    - name: Build
      if: steps.check-tag.outputs.match == 'true'
      run: |
        echo "Tag is a match"
  